zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"

kafka:
  image: wurstmeister/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: kafka.dev
    VIRTUAL_HOST: kafka.dev
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

app:
  image: smebberson/alpine-nginx
  volumes:
    - ./web-app/dist:/usr/html
  ports:
    - 443
    - 80
