version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "example-topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: postgres

  server:
    build: ./server

  incrementer:
    build: ./incrementer

  entry:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    links:
      - server:api

  app:
    build: ./web-app
    volumes:
      - ./web-app/dist:/usr/html
