zookeeper:
  image: wurstmeister/zookeeper
  ports: 
    - "2181:2181"

kafka:
  image: wurstmeister/kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 192.168.99.101
    KAFKA_CREATE_TOPICS: "example-topic:1:1"
    KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

db:
  image: postgres

server:
  build: ./server
  links:
    - db
    - kafka
  ports:
    - 4567:4567

incrementer:
  build: ./incrementer
  links:
    - db
    - kafka
    - zookeeper

entry:
  build: ./nginx
  links:
    - app
    - "server:api"
  ports:
    - "443:443"
    - "80:80"

app:
  build: ./web-app
  links:
    - server
  volumes:
    - ./web-app/dist:/usr/html
  ports:
    - 443
    - 80
