version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "hodder.todos:1:1"
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  kafka-monitor:
    build: kafka-monitor
    ports:
      - 8080
    depends_on:
      - zookeeper

  db:
    image: postgres

  server:
    build: ./server
    depends_on:
      - db
      - kafka

  todo-consumer:
    build: ./todo-consumer
    depends_on:
      - db
      - kafka

  entry:
    build: ./nginx
    ports:
      - "443:443"
      - "80:80"
    links:
      - server:api

  app:
    build: ./web-app
    volumes:
      - ./web-app/dist:/usr/html
